name: Deploy FruitFall NodeJS App 

on:
  workflow_dispatch:
    
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  deploy_fruitfall_nodejs_app:
    runs-on: ["self-hosted","ub22"]  

    steps:

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Deploy node.js app via pm2 
      run: |
        # Restart our Fruitfall Node.js app using PM2
        echo "Restarting NodeJS app using PM2"        
        pm2 restart fruitfall 

        # Restart Nginx web server and reverse proxy
        echo "Restarting nginx web service and reverse proxy"
        sudo systemctl restart nginx 
        sudo systemctl status nginx 
